<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta charset="utf-8" />
  <link rel="icon" href="/images/logo.png" />
  <meta name="keywords" content="Магазин комнатных растений" />
  <meta name="description" content="Магазин комнатных растений" />
  <title>Магазин комнатных растений</title>
  <link rel="stylesheet" href="/index.css" media="screen" />
  <link id="u-theme-google-font" rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i" />
  <meta name="theme-color" content="#2f55b0" />
  <meta property="og:title" content="Магазин комнатных растений" />
  <meta property="og:type" content="website" />
  <link rel="canonical" href="/" />
</head>