<div class="sidebar-container">
        <a href="index.html" class="sidebar-item">
          <img src="./images/sidebar-logo.png" />
          <p>Главная страница</p></a
        >
        <a href="index.html" class="sidebar-subitem">
          <p>Цветущие</p>
        </a>
        <a href="trees.html" class="sidebar-subitem">
          <p>Деревья</p>
        </a>
        <a href="succulents.html" class="sidebar-subitem">
          <p>Суккуленты</p>
        </a>
        <a href="about-author.html" class="sidebar-item">
          <img src="./images/sidebar-logo.png" />
          <p>Об авторе</p></a
        >
        <a href="about-company.html" class="sidebar-item">
          <img src="./images/sidebar-logo.png" />
          <p>О фирме</p></a
        >
      </div>