<div class="sidebar-container">
  <a href="/" class="sidebar-item">
    <img src="/images/sidebar-logo.png" />
    <p>Главная страница</p>
  </a>
  <a href="/" class="sidebar-subitem">
    <p>Цветущие</p>
  </a>
  <a href="/trees" class="sidebar-subitem">
    <p>Деревья</p>
  </a>
  <a href="/succulents" class="sidebar-subitem">
    <p>Суккуленты</p>
  </a>
  <a href="/about-author" class="sidebar-item">
    <img src="/images/sidebar-logo.png" />
    <p>Об авторе</p>
  </a>
  <a href="/about-company" class="sidebar-item">
    <img src="/images/sidebar-logo.png" />
    <p>О фирме</p>
  </a>
</div>